version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

  redis:
    image: redis:6.2-buster
    ports:
      - "6379:6379"

  # minio:
  #   image: minio/minio
  #   ports:
  #     - "9001:9001"
  #     - "9002:9002"
  #   volumes:
  #     - /Users/respawn/minio-data:/export
  #   environment:
  #     MINIO_ROOT_USER: minioadmin
  #     MINIO_ROOT_PASSWORD: minioadmin
  #   command: server /export --address :9001 --console-address :9002

  ffmpeg:
    image: jrottenberg/ffmpeg
    volumes:
      - ./public/videos:/videos
    command: ffmpeg -i /videos/input.mp4 -c:v libx264 -crf 18 /videos/output.mp4

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
